# Generated by Django 4.2.3 on 2023-08-18 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaserSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('wavelength', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MetalMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LaserMarkingParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanning_speed', models.PositiveIntegerField()),
                ('average_power', models.DecimalField(decimal_places=2, max_digits=5)),
                ('laser_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.lasersource')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.metalmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='LaserColorMarking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_step', models.FloatField()),
                ('pulse_duration', models.FloatField()),
                ('pulse_repetition_rate', models.PositiveIntegerField()),
                ('overlap_coefficient', models.FloatField()),
                ('volumetric_density_of_energy', models.FloatField()),
                ('color_red', models.PositiveIntegerField()),
                ('color_green', models.PositiveIntegerField()),
                ('color_blue', models.PositiveIntegerField()),
                ('marking_parameters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.lasermarkingparameters')),
            ],
        ),
    ]
