# Generated by Django 4.2.3 on 2023-08-19 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lasermarkingparameters',
            old_name='blue_channel',
            new_name='color_blue',
        ),
        migrations.RenameField(
            model_name='lasermarkingparameters',
            old_name='green_channel',
            new_name='color_green',
        ),
        migrations.RenameField(
            model_name='lasermarkingparameters',
            old_name='red_channel',
            new_name='color_red',
        ),
    ]
