# Generated by Django 4.2.3 on 2023-08-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lasermarkingparameters',
            name='overlap_coefficient',
            field=models.FloatField(default=0.0),
        ),
    ]
