# Generated by Django 4.2.3 on 2023-08-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_lasermarkingparameters_overlap_coefficient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lasermarkingparameters',
            name='color_blue',
            field=models.PositiveIntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='lasermarkingparameters',
            name='color_green',
            field=models.PositiveIntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='lasermarkingparameters',
            name='color_red',
            field=models.PositiveIntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='lasermarkingparameters',
            name='focus',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='lasermarkingparameters',
            name='pulse_duration',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='lasermarkingparameters',
            name='pulse_repetition_rate',
            field=models.PositiveIntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='lasermarkingparameters',
            name='scan_step',
            field=models.FloatField(default=0.0),
        ),
    ]
