# Generated by Django 4.2.3 on 2023-08-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_lasermarkingparameters_color_blue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lasermarkingparameters',
            name='color_blue',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lasermarkingparameters',
            name='color_green',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lasermarkingparameters',
            name='color_red',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lasermarkingparameters',
            name='focus',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lasermarkingparameters',
            name='overlap_coefficient',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lasermarkingparameters',
            name='pulse_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lasermarkingparameters',
            name='pulse_repetition_rate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lasermarkingparameters',
            name='scan_step',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
