# Generated by Django 4.2.3 on 2023-08-30 07:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaserSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type_of_laser', models.CharField(max_length=100)),
                ('wavelength', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LaserMarkingParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanning_speed', models.PositiveIntegerField()),
                ('average_power', models.DecimalField(decimal_places=2, max_digits=5)),
                ('scan_step', models.FloatField(blank=True, null=True)),
                ('pulse_duration', models.FloatField(blank=True, null=True)),
                ('pulse_repetition_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('overlap_coefficient', models.FloatField(blank=True, null=True)),
                ('volumetric_density_of_energy', models.FloatField(blank=True, null=True)),
                ('focus', models.FloatField(blank=True, null=True)),
                ('color_red', models.PositiveIntegerField(blank=True, null=True)),
                ('color_green', models.PositiveIntegerField(blank=True, null=True)),
                ('color_blue', models.PositiveIntegerField(blank=True, null=True)),
                ('authors', models.CharField(max_length=100)),
                ('research_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('laser_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laser_color_marking_db.lasersource')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laser_color_marking_db.material')),
            ],
        ),
    ]
