# Generated by Django 4.2.3 on 2023-08-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laser_color_marking_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lasermarkingparameters',
            name='calculated_beam_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lasermarkingparameters',
            name='calculated_brightness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lasermarkingparameters',
            name='calculated_brightness_color',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lasermarkingparameters',
            name='calculated_color_intensity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lasermarkingparameters',
            name='calculated_energy_density',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lasermarkingparameters',
            name='calculated_intensity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lasermarkingparameters',
            name='calculated_power_density',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lasermarkingparameters',
            name='calculated_pulse_energy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lasermarkingparameters',
            name='calculated_repetition_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lasermarkingparameters',
            name='calculated_volumetric_density_of_energy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lasermarkingparameters',
            name='calculated_volumetric_energy_density',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
