# Generated by Django 4.2.7 on 2024-06-09 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laser_color_marking_db', '0002_lasermarkingparameters_calculated_beam_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lasermarkingparameters',
            name='calculated_beam_area',
        ),
        migrations.RemoveField(
            model_name='lasermarkingparameters',
            name='calculated_brightness',
        ),
        migrations.RemoveField(
            model_name='lasermarkingparameters',
            name='calculated_brightness_color',
        ),
        migrations.RemoveField(
            model_name='lasermarkingparameters',
            name='calculated_color_intensity',
        ),
        migrations.RemoveField(
            model_name='lasermarkingparameters',
            name='calculated_energy_density',
        ),
        migrations.RemoveField(
            model_name='lasermarkingparameters',
            name='calculated_intensity',
        ),
        migrations.RemoveField(
            model_name='lasermarkingparameters',
            name='calculated_power_density',
        ),
        migrations.RemoveField(
            model_name='lasermarkingparameters',
            name='calculated_pulse_energy',
        ),
        migrations.RemoveField(
            model_name='lasermarkingparameters',
            name='calculated_repetition_rate',
        ),
        migrations.RemoveField(
            model_name='lasermarkingparameters',
            name='calculated_volumetric_density_of_energy',
        ),
        migrations.RemoveField(
            model_name='lasermarkingparameters',
            name='calculated_volumetric_energy_density',
        ),
    ]
